### PR TITLE
Update comment if exists

### PR DESCRIPTION
**Pull request by int128**

### CODE REVIEW

**Comment by sasa-tomic** [comment]
Any chance this will be merged soon @int128 ? It would be awesome if we had this functionality!

**Comment by int128** [comment]
Thanks. I will continue to implement this feature.

**Comment by int128** [comment]
Implemented as https://github.com/int128/diff-action/pull/694

**Comment by sasa-tomic** [comment]
Thanks so much for implementing this so quickly! This gh action rocks!

**Pull request closed without merging**
